import { feature } from "topojson-client";
import type { Topology } from "topojson-specification";

/**
 * Builds src/designs/signal/scene/land.ts: a small map of the Earth for the
 * Signal globe, one cell per degree. Each cell is ocean, land, or one of the
 * countries the globe's arcs reach. Run it after changing the destinations:
 *   bun scripts/globe-land.ts
 * Country shapes: Natural Earth 1:50m, via the world-atlas package.
 */

const OUT = "src/designs/signal/scene/land.ts";
const COLS = 360;
const ROWS = 180;

// ISO 3166 numeric codes. Keep in step with the cities in globe() (scene/field.ts).
const REACHED: Record<string, string> = {
  "608": "Philippines",
  "124": "Canada",
  "702": "Singapore",
  "392": "Japan",
  "840": "United States",
  "826": "United Kingdom",
  "036": "Australia",
  "276": "Germany",
  "356": "India",
};
// Too small to cover a cell centre; the cell holding the city is marked by hand.
const SPECKS: [number, number][] = [[1.35, 103.82]];

const OCEAN = 0;
const LAND = 1;
const REACH = 2;

type Ring = number[][];

const topo = (await Bun.file("node_modules/world-atlas/countries-50m.json").json()) as Topology;
const grid = new Uint8Array(COLS * ROWS);

/** Fills every cell whose centre lies inside the rings (even-odd), one scanline per row. */
function fill(rings: Ring[], value: number) {
  for (let row = 0; row < ROWS; row++) {
    const lat = 90 - row - 0.5;
    const xs: number[] = [];
    for (const ring of rings) {
      for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
        const [x1, y1] = ring[j];
        const [x2, y2] = ring[i];
        if (y1 > lat !== y2 > lat) xs.push(x1 + ((lat - y1) / (y2 - y1)) * (x2 - x1));
      }
    }
    xs.sort((a, b) => a - b);
    for (let k = 0; k + 1 < xs.length; k += 2) {
      const from = Math.ceil(xs[k] + 180 - 0.5);
      const to = Math.floor(xs[k + 1] + 180 - 0.5);
      for (let col = Math.max(0, from); col <= Math.min(COLS - 1, to); col++) grid[row * COLS + col] = value;
    }
  }
}

const countries = feature(topo, topo.objects.countries) as unknown as GeoJSON.FeatureCollection;
const polygons = (geometry: GeoJSON.Geometry): Ring[][] =>
  geometry.type === "Polygon" ? [geometry.coordinates] : geometry.type === "MultiPolygon" ? geometry.coordinates : [];

for (const country of countries.features) for (const rings of polygons(country.geometry)) fill(rings, LAND);
for (const country of countries.features) {
  if (!(String(country.id) in REACHED)) continue;
  for (const rings of polygons(country.geometry)) fill(rings, REACH);
}
for (const [lat, lon] of SPECKS) grid[Math.floor(90 - lat) * COLS + Math.floor(lon + 180)] = REACH;

// Run-length encoded, row by row: each run is its value followed by its length in two base-36 digits.
let encoded = "";
for (let row = 0; row < ROWS; row++) {
  let col = 0;
  while (col < COLS) {
    const value = grid[row * COLS + col];
    let length = 1;
    while (col + length < COLS && grid[row * COLS + col + length] === value) length++;
    encoded += value + length.toString(36).padStart(2, "0");
    col += length;
  }
}

const names = Object.values(REACHED).join(", ");
await Bun.write(
  OUT,
  `// Generated by scripts/globe-land.ts from Natural Earth (public domain). Do not edit.

/**
 * The Earth at one cell per degree, rows from 90°N, columns from 180°W. Cells are
 * 0 ocean, 1 land, or 2 a country the globe's arcs reach (${names}).
 */
export const LAND_COLS = ${COLS};
export const LAND_ROWS = ${ROWS};

const RUNS =
  "${encoded}";

/** Expands the map into one byte per cell. */
export function landGrid(): Uint8Array {
  const grid = new Uint8Array(LAND_COLS * LAND_ROWS);
  let at = 0;
  for (let i = 0; i < RUNS.length; i += 3) {
    const length = parseInt(RUNS.slice(i + 1, i + 3), 36);
    grid.fill(RUNS.charCodeAt(i) - 48, at, at + length);
    at += length;
  }
  return grid;
}
`,
);
console.log(`wrote ${OUT}: ${encoded.length} chars, ${grid.filter((v) => v === LAND).length} land cells, ${grid.filter((v) => v === REACH).length} reached`);
